# Database connection
DbConnection = "user=walmart_user password=securepassword host=localhost dbname=walmart_db"

# Close pooled connections after this interval
DbPoolMaxConnLifeTime = "3h"

# Hold no more than this number of connections in the database pool
DbPoolMaxConns = 4

# Look to read html templates from this directory
# AssetsPath = "/usr/share/pg_tileserv/assets"

# Accept connections on this subnet (default accepts on all)
HttpHost = "0.0.0.0"

# Accept connections on this port
HttpPort = 7800
HttpsPort = 7801
